---
title: "debugging script"
author: "William Norfolk"
date: "6/3/2020"
output: html_document
---

```{r}
library(tidyverse)
library(readr)
library(here)
library(readxl)
library(stringr)
library(tm)
```

```{r}
us_popsize <-readRDS("../data/us_popsize.rds")  %>% rename(state_abr = state, state = state_full)
world_popsize <-readRDS("../data/world_popsize.rds") 
county_popsize <- readRDS("../data/county_popsize.rds")


```

```{r}
  #################################
  # pull state level and testing data from Covidtracking and process
  #################################
  us_ct_data <- read_csv("https://covidtracking.com/api/v1/states/daily.csv")
  us_ct_clean <- us_ct_data %>% dplyr::select(c(date,state,positive,negative,total,hospitalized,death)) %>%
    mutate(date = as.Date(as.character(date),format="%Y%m%d")) %>% 
    group_by(state) %>% 
    arrange(date) %>%
    mutate(Daily_Test_Positive = c(0,diff(positive))) %>% 
    mutate(Daily_Test_Negative = c(0,diff(negative))) %>% 
    mutate(Daily_Test_All = c(0,diff(total))) %>% 
    mutate(Daily_Hospitalized = c(0,diff(hospitalized))) %>% 
    mutate(Daily_Deaths = c(0,diff(death))) %>% 
    rename(state_abr = state) %>%
    merge(us_popsize) %>%
    rename(Date = date, Location = state, Population_Size = total_pop, Total_Deaths = death, 
           Total_Cases = positive, Total_Hospitalized = hospitalized, 
           Total_Test_Negative = negative, Total_Test_Positive = positive, Total_Test_All = total) %>%
    mutate(Daily_Cases = Daily_Test_Positive, Total_Cases = Total_Test_Positive) %>%
    mutate(Daily_Positive_Prop = Daily_Test_Positive / Daily_Test_All) %>%
    mutate(Total_Positive_Prop = Total_Test_Positive / Total_Test_All) %>%
    select(-c(state_abr,Total_Test_Negative,Daily_Test_Negative))
  
  #add all US by summing over all variables
  #adding is not right approach for proportion test positive, so need to recompute
  all_us <- us_ct_clean %>% group_by(Date) %>% 
                            summarize_if(is.numeric, sum, na.rm=TRUE) %>%
                            mutate(Location = "US") %>%
                            mutate(Population_Size = max(Population_Size)) %>%
                            mutate(Daily_Positive_Prop = Daily_Test_Positive / Daily_Test_All) %>%
                            mutate(Total_Positive_Prop = Total_Test_Positive / Total_Test_All) 
    
  #combine all US data with rest of data
  us_ct_clean = rbind(us_ct_clean,all_us)
  
  #reformat to long
  us_ct_clean <- gather(us_ct_clean, variable, value, -Location, -Population_Size, -Date)
  
  #*************************************
  #I don't understand why this aggregation is done here   
  #Are there duplicate values? If yes, shouldn't we remove the duplicates instead of summing?
  #*************************************
# ANSWER: You are correct, this aggregation is not needed. I did a second search for duplicated entries and was not able to find any so I removed this line from the app_new file in the new push.

 # us_ct_clean <- aggregate(value ~ Date + Location + Population_Size + variable, us_ct_clean, FUN = sum)
  us_ct_clean$value[!is.finite(us_ct_clean$value)] <- NA
  us_ct_clean <- na.omit(us_ct_clean)
```


```{r}
  #################################
  # pull data from USAFacts and process
  #################################
  #pull data
  usafct_case_data <- readr::read_csv("https://usafactsstatic.blob.core.windows.net/public/data/covid-19/covid_confirmed_usafacts.csv")
  usafct_death_data <- readr::read_csv("https://usafactsstatic.blob.core.windows.net/public/data/covid-19/covid_deaths_usafacts.csv")
  
  state_df = usafct_case_data %>% 
             distinct(stateFIPS, .keep_all = TRUE) %>% 
             select(State,stateFIPS)

  usafct_case_clean <- usafct_case_data %>% 
                      dplyr::group_by(stateFIPS) %>% 
                      summarize_if(is.numeric, sum, na.rm=TRUE) %>%
                      dplyr::select(-countyFIPS) %>% 
                      left_join(state_df) %>%    
                      tidyr::pivot_longer(-State, names_to = "Date", values_to = "Total_Cases") %>%
                      mutate(Date = as.Date(Date,format="%m/%d/%y")) %>% 
                      group_by(State) %>% arrange(Date) %>%
                      mutate(Daily_Cases = c(0,diff(Total_Cases))) %>% 
                      rename(state_abr = State) %>%
                      merge(us_popsize) %>%
                      rename(Location = state, Population_Size = total_pop) %>%
                      select(-c(state_abr))
  
  usafct_death_clean <- usafct_death_data %>% 
                        dplyr::group_by(stateFIPS) %>% 
                        summarize_if(is.numeric, sum, na.rm=TRUE) %>%
                        dplyr::select(-countyFIPS) %>% 
                        left_join(state_df) %>%    
                        tidyr::pivot_longer(-State, names_to = "Date", values_to = "Total_Deaths") %>%
                        mutate(Date = as.Date(Date,format="%m/%d/%y")) %>% 
                        group_by(State) %>% arrange(Date) %>%
                        mutate(Daily_Deaths = c(0,diff(Total_Deaths))) %>% 
                        rename(state_abr = State) %>%
                        merge(us_popsize) %>%
                        rename(Location = state, Population_Size = total_pop) %>%
                        select(-c(state_abr))
                      
  usafct_clean <- left_join(usafct_case_clean, usafct_death_clean) %>%
                  group_by(Location) %>% 
                  arrange(Date)  %>%
                  ungroup()
                
  
  #*************************************
  #Why is us_popsize merged with the data frame below and not county_popsize?
  #same for deaths below
  #*************************************
  #ANSWER: My apologies I meant to fix that issue before pushing my prior change. I am not exactly sure what my   thought process was here, I modified the code below to simply join with the county_popsize data. I added these changes to the new push of app_new.R
  
  #County data cleaning-cases
   usafct_case_data$State <- state.name[match(usafct_case_data$State, state.abb)]

  county_usafct_case <- usafct_case_data %>% 
                        select(-c(countyFIPS, stateFIPS)) %>%
                        rename(Location = State, county_name = `County Name`) %>%
                        dplyr::filter(county_name != "Statewide Unallocated") %>%
                        gather(Date, Total_Cases, -Location, -county_name) %>%
                        mutate(Date = as.Date(Date,format="%m/%d/%y")) %>%
                        group_by(Location, county_name) %>% arrange(Date) %>%
                        mutate(Daily_Cases = c(0,diff(Total_Cases))) 
  #remove words to match county level population values
  remove_words <- c(" County", " Borough", " Census Area", "Municipality of "," City and Borough", " County and City", " Parish", " Municipality")
  county_usafct_case$county_name <- tm::removeWords(county_usafct_case$county_name, remove_words)
  county_usafct_case_clean <- merge(county_usafct_case, county_popsize) 
  
  #County data cleaning-deaths
     usafct_death_data$State <- state.name[match(usafct_death_data$State, state.abb)]
  county_usafct_death <- usafct_death_data %>% 
                         select(-c(countyFIPS, stateFIPS)) %>%
                        rename(Location = State, county_name = `County Name`) %>%
                        dplyr::filter(county_name != "Statewide Unallocated") %>%
                        gather(Date, Total_Deaths, -Location, -county_name) %>%
                        mutate(Date = as.Date(Date,format="%m/%d/%y")) %>%
                        group_by(Location, county_name) %>% arrange(Date) %>%
                        mutate(Daily_Deaths = c(0,diff(Total_Deaths))) 
  #remove words to match county level population values
  county_usafct_death$county_name <- tm::removeWords(county_usafct_death$county_name, remove_words)
  county_usafct_death_clean <- merge(county_usafct_death, county_popsize)
  
  #combine county data
  county_usafct_clean <- merge(county_usafct_case_clean, county_usafct_death_clean) %>%
                         rename(Population_Size = population_size)
  
  #reformat county to long
  county_usafct_clean <- gather(county_usafct_clean, variable, value, -county_name, -Location, -Date, -Population_Size)
  
  #add all US by summing over all variables
  all_us <- usafct_clean %>% 
            group_by(Date) %>% 
            summarize_if(is.numeric, sum, na.rm=TRUE) %>%
            mutate(Location = "US") %>%
            mutate(Population_Size = max(Population_Size))
  
  usafct_clean = rbind(usafct_clean,all_us)
  #reformat to long
  usafct_clean <- gather(usafct_clean, variable, value, -Location, -Population_Size, -Date)
```

```{r}
  #################################
  # pull US data from JHU github and process
  #################################
  us_jhu_cases <- readr::read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv")
  us_jhu_deaths <- read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv")
  # Clean cases
  us_jhu_cases <- us_jhu_cases %>% 
                  filter(iso3 == "USA") %>%
                  dplyr::select(c(-Country_Region, -Lat, -Long_, -UID, -iso2, -iso3, -code3, -Combined_Key)) %>%
                  rename(Location = Province_State)
  
  #*************************************
  #What does the aggregate function below do, why is it needed?
  #*************************************
  #ANSWER: It is actually not needed anymore! This line is a relic of the older version (without county-level data) that aggregated the values for each states. I must have missed it when coding in the county cleaning. I deleted it on the new push of app_new.R.  
  
  #us_jhu_cases <- aggregate(. ~ Location + FIPS + Admin2, us_jhu_cases, FUN = sum)
  us_jhu_cases_clean <- gather(us_jhu_cases, Date, Cases, -Location, -FIPS, -Admin2)
  # Clean deaths
  us_jhu_deaths <- us_jhu_deaths %>% filter(iso3 == "USA") %>%
    dplyr::select(c(-Country_Region, -Lat, -Long_, -UID, -iso2, -iso3, -code3, -Combined_Key, -Population)) %>%
    rename(Location = Province_State)
  us_jhu_deaths <- aggregate(. ~ Location + FIPS + Admin2, us_jhu_deaths, FUN = sum)
  us_jhu_deaths_clean <- gather(us_jhu_deaths, Date, Deaths, -Location, -FIPS, Admin2)
  us_jhu_combined <- merge(us_jhu_cases_clean, us_jhu_deaths_clean)
  us_jhu_combined$Deaths <- as.numeric(as.character(us_jhu_combined$Deaths))
  us_jhu_popsize <- us_popsize %>% rename(Location = state)
  # This merge removes cruise ship cases/death counts
  us_jhu_merge <- merge(us_jhu_combined, us_jhu_popsize)
  us_jhu_total <- us_jhu_merge %>% mutate(Date = as.Date(as.character(Date),format="%m/%d/%y")) %>%
    group_by(Location, Admin2) %>% arrange(Date) %>%
    mutate(Daily_Cases = c(0,diff(Cases))) %>%
    mutate(Daily_Deaths = c(0,diff(Deaths))) %>% 
    ungroup() %>%
    rename(Total_Deaths = Deaths, Total_Cases = Cases, Population_Size = total_pop, county_name = Admin2) %>% 
    select(-state_abr) 
  
  #Use us_jhu_total to create both the county and state level datasets 
  #Pull county data and reformat to long
  county_jhu_clean <- gather(us_jhu_total, variable, value, -Location, -Population_Size, -Date, -FIPS, -county_name) 
  #add county population numbers 
  county_jhu_clean <- merge(county_jhu_clean, county_popsize) %>%
    select(-c(Population_Size, FIPS)) %>%
    rename(Population_Size = population_size)
  
  #pull state data and aggregate county values
  us_jhu_clean <- us_jhu_total %>% select(-FIPS, -county_name)
  us_jhu_clean <- aggregate(. ~ Location + Date + Population_Size, us_jhu_clean, FUN = sum)
  
  #add total US values
  #*************************************
  #No longer need the syntax: mutate(Population_Size = max(Population_Size)) in the all_us code since values     are aggregated in the lines above. This was the source of the US 100K scaled error. It has been removed in     the new push to app_new.
  #*************************************
  all_us <- us_jhu_clean %>% group_by(Date) %>% summarize_if(is.numeric, sum, na.rm=TRUE)
  all_us$Location = "US"
  us_jhu_clean = rbind(us_jhu_clean,all_us)
  #reformat state data to long
  us_jhu_clean <- gather(us_jhu_clean, variable, value, -Location, -Population_Size, -Date)
  
```




