---
title: "world_pop_prep"
author: "William Norfolk"
date: "4/2/2020"
output: html_document
---

```{r}

library(tidyverse)
library(readxl)
library(tm)

```

```{r}
#Create world population RDS

world_pop <- readxl::read_excel("./world_pops_modified.xlsx")
world_pop <- world_pop %>% 
  dplyr::mutate(country_pop = country_pop_in_thousands * 1000) %>%
  dplyr::select(c(country, country_pop))

```

```{r}
world_pop <- aggregate(country_pop ~ country, world_pop, FUN = sum)
```

```{r}
saveRDS(world_pop, file = "../world_popsize.rds")
```

```{r}
us_pop <- readxl::read_excel("./us_pop.xlsx")
```

```{r}
saveRDS(us_pop, file = "../us_popsize.rds")
```

```{r}
#create county level population data from 2019 census database
remove_words <- c("County", "Parish", "city", "City", "Census Area", "Borough", "Municipality", "City and Borough")
county_pop <- readxl::read_excel("./county_pop.xlsx")
county_pop$county_name <- gsub('^.', '', county_pop$county_name)
county_pop$county_name <- removeWords(county_pop$county_name, remove_words)
county_pop <- separate(county_pop, col = county_name, into = c("county_name","Location"), sep = " , ")

saveRDS(county_pop, file = "../../data/county_popsize.rds")
```



